version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/app

jobs:
  checkout_code:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  dependencies:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - deps-v1-{{ .Branch }}
            - deps-v1-
      - run:
          name: Install NPM dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn run build

  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn run test
  #      - run:
  #          name: Send coverage report
  #          command: cat coverage/lcov.info | yarn coveralls
  #      - store_test_results:
  #          when: always
  #          path: test-results

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run linting
          command: yarn run lint
#      - store_test_results:
#          when: always
#          path: test-results

workflows:
  version: 2
  build_test_lint:
    jobs:
      - checkout_code
      - dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
