dist: xenial
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: "Compile, Lint, and Test"
      script: yarn build
    - script: yarn lint
    - script:
        - yarn run test:coverage
        - cat coverage/lcov.info | yarn coveralls
