import { readFileSync } from 'fs'
import { resolve } from 'path'
import { printSchema } from 'graphql'

import { createSchema } from '@/graphql/index'

const disclaimer = `
# -----------------------------------------------
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------

`.trimStart()

test('generated schema should be identical to snapshot', async () => {
  const snapshot = readFileSync(
    resolve(__dirname, 'snapshot.graphql'),
  ).toString()

  const schema = await createSchema(false)
  const schemaSDL = printSchema(schema)

  expect(disclaimer + schemaSDL).toEqual(snapshot)
})
